apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # these are replica set labels
  labels:
      project: roboshop
      component: mongodb
      tier: backend
spec:
  replicas: 1
  # replicas: 10
  selector:
    #  these labels are used to select pods
    matchLabels:
      project: roboshop
      component: mongodb
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: backend
    spec:
      containers:
      - name: mongodb
        image: vijayamudalapalli/mongodb:v1
        # image: nginx
        # image: nginx:trixie-perl
        # image: nginx:latest
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mongodb
    tier: backend
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 8270170 # container port
